<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4I73VKF" ignored="0" name="TestNGTest1" tests="2" failures="1" timestamp="2020-07-17T12:02:04 IST" time="0.077" errors="0">
  <testcase name="test1m2" time="0.007" classname="org.trial.test.Test1"/>
  <testcase name="test1m1" time="0.009" classname="org.trial.test.Test1">
    <failure type="java.lang.AssertionError" message="Failed">
      <![CDATA[java.lang.AssertionError: Failed
at org.trial.test.Test1.test1m1(Test1.java:19)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- test1m1 -->
</testsuite> <!-- TestNGTest1 -->
