<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4I73VKF" ignored="1" name="TestNGTest1(failed)" tests="1" failures="1" timestamp="2020-07-17T12:14:34 IST" time="0.094" errors="0">
  <testcase name="test1m1" time="0.01" classname="org.trial.test.Test1">
    <failure type="java.lang.AssertionError" message="Failed">
      <![CDATA[java.lang.AssertionError: Failed
at org.trial.test.Test1.test1m1(Test1.java:19)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- test1m1 -->
  <testcase name="test1m2" time="0.0" classname="org.trial.test.Test1">
    <ignored/>
  </testcase> <!-- test1m2 -->
</testsuite> <!-- TestNGTest1(failed) -->
